<?xml version="1.0" encoding="UTF-8"?>
<root>
   <element>
      <faces>1</faces>
      <locations>
         <element>
            <h>119</h>
            <w>119</w>
            <x>33</x>
            <y>23</y>
         </element>
      </locations>
      <name>Scan%205.jpeg</name>
   </element>
   <element>
      <faces>0</faces>
      <name>Scan%204.jpeg</name>
   </element>
</root>
